// Generated by scripts/build-aliases.mjs from the supplied alias inventories.
export const aliasData = [
  {
    "id": "character:adi-varma",
    "name": "Adi Varma",
    "category": "character",
    "inputs": [
      "Adi Varma",
      "Adi",
      "Ardee",
      "Ardee Varma"
    ],
    "printed": [
      "Adi",
      "Adi Varma",
      "Ardee",
      "Ardee Varma"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:aina-lindle",
    "name": "Aina Lindle",
    "category": "character",
    "inputs": [
      "Aina Lindle",
      "Aina",
      "Aina Tulle"
    ],
    "printed": [
      "Aina",
      "Aina Lindle"
    ],
    "optional": [],
    "caution": "Some names or spellings can have other meanings. Check the surrounding context."
  },
  {
    "id": "character:ais-wallenstein",
    "name": "Ais Wallenstein",
    "category": "character",
    "inputs": [
      "Ais Wallenstein",
      "Aiz",
      "Aiz Wallenstein",
      "Ais",
      "Sword Princess",
      "War Princess",
      "Doll Princess",
      "Aizuu",
      "Aizuuu",
      "kenki",
      "senki",
      "lady of the sword",
      "lady of combat",
      "lady of the battlefield",
      "Wallenstein"
    ],
    "printed": [
      "Aiz",
      "Aiz Wallenstein",
      "Ais",
      "Sword Princess",
      "War Princess",
      "Doll Princess",
      "Aizuu",
      "Aizuuu",
      "kenki",
      "senki",
      "lady of the sword",
      "lady of combat",
      "lady of the battlefield"
    ],
    "optional": [
      {
        "form": "Wallenstein",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:aisha-belka",
    "name": "Aisha Belka",
    "category": "character",
    "inputs": [
      "Aisha Belka",
      "Aisha",
      "Antianeira"
    ],
    "printed": [
      "Aisha Belka",
      "Aisha",
      "Antianeira"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:albert-the-great",
    "name": "Albert the Great",
    "category": "character",
    "inputs": [
      "Albert the Great",
      "Albert",
      "Mercenary King",
      "Eusebius",
      "Valdstejn",
      "Albehrt Eusebius",
      "Champion of the Sword",
      "Sword Champion"
    ],
    "printed": [
      "Albert the Great",
      "Albert",
      "Mercenary King",
      "Eusebius",
      "Valdstejn",
      "Albehrt Eusebius",
      "Champion of the Sword"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:alfia",
    "name": "Alfia",
    "category": "character",
    "inputs": [
      "Alfia",
      "Silent Witch",
      "Grand Silent Witch",
      "Silence"
    ],
    "printed": [
      "Alfia",
      "Silent Witch",
      "Grand Silent Witch"
    ],
    "optional": [
      {
        "form": "Silence",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:alfrik",
    "name": "Alfrik",
    "category": "character",
    "inputs": [
      "Alfrik",
      "Bringar",
      "Gulliver brothers",
      "Four Knights of the Golden Flame"
    ],
    "printed": [
      "Alfrik"
    ],
    "optional": [
      {
        "form": "Bringar",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Gulliver brothers",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Four Knights of the Golden Flame",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:ali",
    "name": "Ali",
    "category": "character",
    "inputs": [
      "Ali",
      "Aram",
      "Aram Raza Shalzad"
    ],
    "printed": [
      "Ali"
    ],
    "optional": [
      {
        "form": "Aram",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Aram Raza Shalzad",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:alicia-forestlight",
    "name": "Alicia Forestlight",
    "category": "character",
    "inputs": [
      "Alicia Forestlight",
      "Alicia"
    ],
    "printed": [
      "Alicia",
      "Alicia Forestlight"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:alisa-ragast",
    "name": "Alisa Ragast",
    "category": "character",
    "inputs": [
      "Alisa Ragast",
      "Alisa",
      "Alisa Larghast"
    ],
    "printed": [
      "Alisa",
      "Alisa Ragast"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:alize-lovell",
    "name": "Alize Lovell",
    "category": "character",
    "inputs": [
      "Alize Lovell",
      "Alize",
      "Alizé",
      "Alizé Rovel",
      "Scarlett Harnell",
      "Alise",
      "Alise Lovell",
      "Scarlet Harnel"
    ],
    "printed": [
      "Alize",
      "Alize Lovell",
      "Alizé",
      "Alizé Rovel",
      "Scarlett Harnell"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:allen-fromel",
    "name": "Allen Fromel",
    "category": "character",
    "inputs": [
      "Allen Fromel",
      "Allen",
      "Vana Freya",
      "city’s fastest",
      "Freya’s Chariot"
    ],
    "printed": [
      "Allen Fromel",
      "Allen",
      "Vana Freya"
    ],
    "optional": [
      {
        "form": "city’s fastest",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Freya’s Chariot",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:amid-teasanare",
    "name": "Amid Teasanare",
    "category": "character",
    "inputs": [
      "Amid Teasanare",
      "Amid",
      "Amid Tessanare",
      "Dea Saint",
      "Silver Saint",
      "Airmid",
      "Airmid Teasanare"
    ],
    "printed": [
      "Amid",
      "Amid Teasanare",
      "Amid Tessanare",
      "Dea Saint",
      "Silver Saint"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:anakity-autumn",
    "name": "Anakity Autumn",
    "category": "character",
    "inputs": [
      "Anakity Autumn",
      "Anakity",
      "Anakitty",
      "Anakitty Autumn",
      "Aki",
      "Alsha",
      "Alchat"
    ],
    "printed": [
      "Anakity",
      "Anakity Autumn",
      "Anakitty",
      "Anakitty Autumn",
      "Aki",
      "Alsha"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:anna-kreiz",
    "name": "Anna Kreiz",
    "category": "character",
    "inputs": [
      "Anna Kreiz",
      "Anna"
    ],
    "printed": [
      "Anna Kreiz",
      "Anna"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:anya-fromel",
    "name": "Anya Fromel",
    "category": "character",
    "inputs": [
      "Anya Fromel",
      "Ahnya",
      "Ahnya Fromel",
      "Anya",
      "Vana Alfi"
    ],
    "printed": [
      "Ahnya",
      "Ahnya Fromel",
      "Anya",
      "Vana Alfi"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:aphrodite",
    "name": "Aphrodite",
    "category": "character",
    "inputs": [
      "Aphrodite"
    ],
    "printed": [
      "Aphrodite"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:apollo",
    "name": "Apollo",
    "category": "character",
    "inputs": [
      "Apollo",
      "Phallus"
    ],
    "printed": [
      "Apollo",
      "Phallus"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:aram-raza-shalzad",
    "name": "Aram Raza Shalzad",
    "category": "character",
    "inputs": [
      "Aram Raza Shalzad",
      "Aram"
    ],
    "printed": [
      "Aram Raza Shalzad",
      "Aram"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:arcus",
    "name": "Arcus",
    "category": "character",
    "inputs": [
      "Arcus"
    ],
    "printed": [
      "Arcus"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:ares",
    "name": "Ares",
    "category": "character",
    "inputs": [
      "Ares",
      "God of War"
    ],
    "printed": [
      "Ares"
    ],
    "optional": [
      {
        "form": "God of War",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:argana-kalif",
    "name": "Argana Kalif",
    "category": "character",
    "inputs": [
      "Argana Kalif",
      "Argana",
      "Kalima"
    ],
    "printed": [
      "Argana Kalif",
      "Argana"
    ],
    "optional": [
      {
        "form": "Kalima",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:argonaut",
    "name": "Argonaut",
    "category": "character",
    "inputs": [
      "Argonaut"
    ],
    "printed": [
      "Argonaut"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:artemis",
    "name": "Artemis",
    "category": "character",
    "inputs": [
      "Artemis"
    ],
    "printed": [
      "Artemis"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:aruru",
    "name": "Aruru",
    "category": "character",
    "inputs": [
      "Aruru"
    ],
    "printed": [
      "Aruru"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:asfi-al-andromeda",
    "name": "Asfi Al Andromeda",
    "category": "character",
    "inputs": [
      "Asfi Al Andromeda",
      "Asfi",
      "Perseus",
      "Princess Andromeda"
    ],
    "printed": [
      "Asfi",
      "Asfi Al Andromeda",
      "Perseus",
      "Princess Andromeda"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:asta",
    "name": "Asta",
    "category": "character",
    "inputs": [
      "Asta"
    ],
    "printed": [
      "Asta"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:asterios",
    "name": "Asterios",
    "category": "character",
    "inputs": [
      "Asterios"
    ],
    "printed": [
      "Asterios"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:astrea",
    "name": "Astrea",
    "category": "character",
    "inputs": [
      "Astrea",
      "Astria",
      "Astraea",
      "goddess of justice",
      "Goddess of Justice and Order"
    ],
    "printed": [
      "Astrea",
      "Astria"
    ],
    "optional": [
      {
        "form": "goddess of justice",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Goddess of Justice and Order",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:asuka",
    "name": "Asuka",
    "category": "character",
    "inputs": [
      "Asuka"
    ],
    "printed": [
      "Asuka"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:aura-moriel",
    "name": "Aura Moriel",
    "category": "character",
    "inputs": [
      "Aura Moriel",
      "Aura",
      "Krater"
    ],
    "printed": [
      "Aura Moriel",
      "Aura",
      "Krater"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:bache-kalif",
    "name": "Bache Kalif",
    "category": "character",
    "inputs": [
      "Bache Kalif",
      "Bache"
    ],
    "printed": [
      "Bache Kalif",
      "Bache"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:balder",
    "name": "Balder",
    "category": "character",
    "inputs": [
      "Balder",
      "Baldr"
    ],
    "printed": [
      "Balder"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:barca",
    "name": "Barca",
    "category": "character",
    "inputs": [
      "Barca",
      "Barca Perdix"
    ],
    "printed": [
      "Barca",
      "Barca Perdix"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:bardain",
    "name": "Bardain",
    "category": "character",
    "inputs": [
      "Bardain"
    ],
    "printed": [
      "Bardain"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:basram",
    "name": "Basram",
    "category": "character",
    "inputs": [
      "Basram"
    ],
    "printed": [
      "Basram"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:bell-cranell",
    "name": "Bell Cranell",
    "category": "character",
    "inputs": [
      "Bell Cranell",
      "Bell",
      "Little Rookie",
      "Rabbit Foot",
      "Regulus Arne",
      "Record Holder",
      "Rapi Flemish",
      "Rapi",
      "Bell Cranel",
      "Cranell",
      "Argonaut",
      "Little Argonaut",
      "record holder"
    ],
    "printed": [
      "Bell",
      "Bell Cranell",
      "Little Rookie",
      "Rabbit Foot",
      "Regulus Arne",
      "Rapi Flemish",
      "Rapi"
    ],
    "optional": [
      {
        "form": "Cranell",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Argonaut",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Little Argonaut",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "record holder",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": "Some names or spellings can have other meanings. Check the surrounding context."
  },
  {
    "id": "character:berling",
    "name": "Berling",
    "category": "character",
    "inputs": [
      "Berling",
      "Bringar",
      "Gulliver brothers",
      "Four Knights of the Golden Flame"
    ],
    "printed": [
      "Berling"
    ],
    "optional": [
      {
        "form": "Bringar",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Gulliver brothers",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Four Knights of the Golden Flame",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:bete-loga",
    "name": "Bete Loga",
    "category": "character",
    "inputs": [
      "Bete Loga",
      "Bete",
      "Vanargand",
      "Fenris"
    ],
    "printed": [
      "Bete",
      "Bete Loga",
      "Vanargand"
    ],
    "optional": [
      {
        "form": "Fenris",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:bom-cornwall",
    "name": "Bom Cornwall",
    "category": "character",
    "inputs": [
      "Bom Cornwall",
      "Bom"
    ],
    "printed": [
      "Bom Cornwall",
      "Bom"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:borg-murdock",
    "name": "Borg Murdock",
    "category": "character",
    "inputs": [
      "Borg Murdock",
      "Borg"
    ],
    "printed": [
      "Borg Murdock",
      "Borg"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:bors",
    "name": "Bors",
    "category": "character",
    "inputs": [
      "Bors",
      "Boris",
      "Boris Elder",
      "Bors Elder"
    ],
    "printed": [
      "Bors",
      "Boris",
      "Boris Elder",
      "Bors Elder"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:brigit",
    "name": "Brigit",
    "category": "character",
    "inputs": [
      "Brigit",
      "Brigid"
    ],
    "printed": [
      "Brigit"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:cassandra-illion",
    "name": "Cassandra Illion",
    "category": "character",
    "inputs": [
      "Cassandra Illion",
      "Cassandra",
      "Mirabilis",
      "Cassandra Ilion"
    ],
    "printed": [
      "Cassandra",
      "Cassandra Illion",
      "Mirabilis"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:cecille",
    "name": "Cecille",
    "category": "character",
    "inputs": [
      "Cecille",
      "Cecille Blackliza",
      "Cecil",
      "Cecil Blackliza"
    ],
    "printed": [
      "Cecille",
      "Cecille Blackliza"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:celia",
    "name": "Celia",
    "category": "character",
    "inputs": [
      "Celia"
    ],
    "printed": [
      "Celia"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:celty-srowa",
    "name": "Celty Srowa",
    "category": "character",
    "inputs": [
      "Celty Srowa",
      "Celty"
    ],
    "printed": [
      "Celty Srowa",
      "Celty"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:chandra-ihit",
    "name": "Chandra Ihit",
    "category": "character",
    "inputs": [
      "Chandra Ihit",
      "Chandra"
    ],
    "printed": [
      "Chandra",
      "Chandra Ihit"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:chigusa-hitachi",
    "name": "Chigusa Hitachi",
    "category": "character",
    "inputs": [
      "Chigusa Hitachi",
      "Chigusa",
      "Hitachi Chigusa"
    ],
    "printed": [
      "Chigusa",
      "Chigusa Hitachi"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:chloe-lolo",
    "name": "Chloe Lolo",
    "category": "character",
    "inputs": [
      "Chloe Lolo",
      "Chloe",
      "Chloe Rollo",
      "Lolo",
      "Black Cat"
    ],
    "printed": [
      "Chloe",
      "Chloe Lolo"
    ],
    "optional": [
      {
        "form": "Lolo",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Black Cat",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:christia-elvia",
    "name": "Christia Elvia",
    "category": "character",
    "inputs": [
      "Christia Elvia",
      "Christia"
    ],
    "printed": [
      "Christia Elvia",
      "Christia"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:cole",
    "name": "Cole",
    "category": "character",
    "inputs": [
      "Cole",
      "Cole Kuster"
    ],
    "printed": [
      "Cole"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:crozzo",
    "name": "Crozzo",
    "category": "character",
    "inputs": [
      "Crozzo"
    ],
    "printed": [
      "Crozzo"
    ],
    "optional": [],
    "caution": "Some names or spellings can have other meanings. Check the surrounding context."
  },
  {
    "id": "character:cruz-bussell",
    "name": "Cruz Bussell",
    "category": "character",
    "inputs": [
      "Cruz Bussell",
      "Cruz"
    ],
    "printed": [
      "Cruz Bussell",
      "Cruz"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:daedalus",
    "name": "Daedalus",
    "category": "character",
    "inputs": [
      "Daedalus",
      "Daidaros"
    ],
    "printed": [
      "Daedalus",
      "Daidaros"
    ],
    "optional": [],
    "caution": "Some names or spellings can have other meanings. Check the surrounding context."
  },
  {
    "id": "character:daphne-laulos",
    "name": "Daphne Laulos",
    "category": "character",
    "inputs": [
      "Daphne Laulos",
      "Daphne",
      "Laurus Fuga",
      "Daphne Lauros"
    ],
    "printed": [
      "Daphne",
      "Daphne Laulos",
      "Laurus Fuga"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:demeter",
    "name": "Demeter",
    "category": "character",
    "inputs": [
      "Demeter"
    ],
    "printed": [
      "Demeter"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:dian-cecht",
    "name": "Dian Cecht",
    "category": "character",
    "inputs": [
      "Dian Cecht",
      "Dian"
    ],
    "printed": [
      "Dian Cecht",
      "Dian"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:dionysus",
    "name": "Dionysus",
    "category": "character",
    "inputs": [
      "Dionysus",
      "Enyo"
    ],
    "printed": [
      "Dionysus"
    ],
    "optional": [
      {
        "form": "Enyo",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:dix",
    "name": "Dix",
    "category": "character",
    "inputs": [
      "Dix",
      "Dix Perdix",
      "Hazer"
    ],
    "printed": [
      "Dix",
      "Dix Perdix",
      "Hazer"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:dormul",
    "name": "Dormul",
    "category": "character",
    "inputs": [
      "Dormul"
    ],
    "printed": [
      "Dormul"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:dvalinn",
    "name": "Dvalinn",
    "category": "character",
    "inputs": [
      "Dvalinn",
      "Bringar",
      "Gulliver brothers",
      "Four Knights of the Golden Flame"
    ],
    "printed": [
      "Dvalinn"
    ],
    "optional": [
      {
        "form": "Bringar",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Gulliver brothers",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Four Knights of the Golden Flame",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:edgar",
    "name": "Edgar",
    "category": "character",
    "inputs": [
      "Edgar"
    ],
    "printed": [
      "Edgar"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:ein",
    "name": "Ein",
    "category": "character",
    "inputs": [
      "Ein"
    ],
    "printed": [
      "Ein"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:eina-tulle",
    "name": "Eina Tulle",
    "category": "character",
    "inputs": [
      "Eina Tulle",
      "Eina"
    ],
    "printed": [
      "Eina Tulle",
      "Eina"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:elfy-colette",
    "name": "Elfy Colette",
    "category": "character",
    "inputs": [
      "Elfy Colette",
      "Elfie",
      "Elfy"
    ],
    "printed": [
      "Elfie"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:enyo",
    "name": "Enyo",
    "category": "character",
    "inputs": [
      "Enyo"
    ],
    "printed": [
      "Enyo"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:erebus",
    "name": "Erebus",
    "category": "character",
    "inputs": [
      "Erebus"
    ],
    "printed": [
      "Erebus"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:falgar-batros",
    "name": "Falgar Batros",
    "category": "character",
    "inputs": [
      "Falgar Batros",
      "Falgar"
    ],
    "printed": [
      "Falgar Batros",
      "Falgar"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:fels",
    "name": "Fels",
    "category": "character",
    "inputs": [
      "Fels",
      "Sage",
      "Fool"
    ],
    "printed": [
      "Fels"
    ],
    "optional": [
      {
        "form": "Sage",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Fool",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:fianna",
    "name": "Fianna",
    "category": "character",
    "inputs": [
      "Fianna",
      "Phiana"
    ],
    "printed": [
      "Fianna",
      "Phiana"
    ],
    "optional": [],
    "caution": "Some names or spellings can have other meanings. Check the surrounding context."
  },
  {
    "id": "character:filvis-challia",
    "name": "Filvis Challia",
    "category": "character",
    "inputs": [
      "Filvis Challia",
      "Filvis",
      "Maenad",
      "Maenads",
      "Banshee",
      "Ein"
    ],
    "printed": [
      "Filvis Challia",
      "Filvis",
      "Maenad"
    ],
    "optional": [
      {
        "form": "Banshee",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Ein",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:finn-deimne",
    "name": "Finn Deimne",
    "category": "character",
    "inputs": [
      "Finn Deimne",
      "Finn",
      "Braver",
      "Fynn"
    ],
    "printed": [
      "Finn",
      "Finn Deimne",
      "Braver"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:freya",
    "name": "Freya",
    "category": "character",
    "inputs": [
      "Freya",
      "goddess of beauty",
      "Syr",
      "Syr Flover"
    ],
    "printed": [
      "Freya"
    ],
    "optional": [
      {
        "form": "goddess of beauty",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Syr",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Syr Flover",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:ganesha",
    "name": "Ganesha",
    "category": "character",
    "inputs": [
      "Ganesha",
      "God of the Masses"
    ],
    "printed": [
      "Ganesha",
      "God of the Masses"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:gareth-landrock",
    "name": "Gareth Landrock",
    "category": "character",
    "inputs": [
      "Gareth Landrock",
      "Gareth",
      "Galess",
      "Galess Landrock",
      "Elgarm",
      "Peerless Wall"
    ],
    "printed": [
      "Gareth",
      "Gareth Landrock",
      "Galess",
      "Galess Landrock",
      "Elgarm",
      "Peerless Wall"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:garon-crozzo",
    "name": "Garon Crozzo",
    "category": "character",
    "inputs": [
      "Garon Crozzo",
      "Garon"
    ],
    "printed": [
      "Garon Crozzo",
      "Garon"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:gedo",
    "name": "Gedo",
    "category": "character",
    "inputs": [
      "Gedo",
      "Ged",
      "Ged Raish"
    ],
    "printed": [
      "Gedo"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:goibniu",
    "name": "Goibniu",
    "category": "character",
    "inputs": [
      "Goibniu"
    ],
    "printed": [
      "Goibniu"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:gordon",
    "name": "Gordon",
    "category": "character",
    "inputs": [
      "Gordon"
    ],
    "printed": [
      "Gordon"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:gran",
    "name": "Gran",
    "category": "character",
    "inputs": [
      "Gran"
    ],
    "printed": [
      "Gran"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:grer",
    "name": "Grer",
    "category": "character",
    "inputs": [
      "Grer",
      "Bringar",
      "Gulliver brothers",
      "Four Knights of the Golden Flame"
    ],
    "printed": [
      "Grer"
    ],
    "optional": [
      {
        "form": "Bringar",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Gulliver brothers",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Four Knights of the Golden Flame",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:gros",
    "name": "Gros",
    "category": "character",
    "inputs": [
      "Gros"
    ],
    "printed": [
      "Gros"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:gryuu",
    "name": "Gryuu",
    "category": "character",
    "inputs": [
      "Gryuu",
      "Gryu"
    ],
    "printed": [
      "Gryuu",
      "Gryu"
    ],
    "optional": [],
    "caution": "Some names or spellings can have other meanings. Check the surrounding context."
  },
  {
    "id": "character:guile",
    "name": "Guile",
    "category": "character",
    "inputs": [
      "Guile",
      "Gyle",
      "Guile India"
    ],
    "printed": [
      "Guile",
      "Gyle"
    ],
    "optional": [],
    "caution": "Some names or spellings can have other meanings. Check the surrounding context."
  },
  {
    "id": "character:haruhime-sanjouno",
    "name": "Haruhime Sanjouno",
    "category": "character",
    "inputs": [
      "Haruhime Sanjouno",
      "Haruhime",
      "Sanjyouno Haruhime",
      "Rikkou Kinshu",
      "Sanjouno Haruhime"
    ],
    "printed": [
      "Haruhime",
      "Haruhime Sanjouno",
      "Sanjyouno Haruhime",
      "Rikkou Kinshu"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:hashana-dorlia",
    "name": "Hashana Dorlia",
    "category": "character",
    "inputs": [
      "Hashana Dorlia",
      "Hashana",
      "Strong Fist Warrior",
      "Hard Fist Fighter"
    ],
    "printed": [
      "Hashana Dorlia",
      "Hashana",
      "Strong Fist Warrior"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:hathor",
    "name": "Hathor",
    "category": "character",
    "inputs": [
      "Hathor"
    ],
    "printed": [
      "Hathor"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:hedin-selrand",
    "name": "Hedin Selrand",
    "category": "character",
    "inputs": [
      "Hedin Selrand",
      "Hedin",
      "Hedin Selland",
      "Hildsleif",
      "Hildrsleif",
      "black and white knights"
    ],
    "printed": [
      "Hedin",
      "Hedin Selrand",
      "Hedin Selland",
      "Hildsleif"
    ],
    "optional": [
      {
        "form": "black and white knights",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:hegni-ragnar",
    "name": "Hegni Ragnar",
    "category": "character",
    "inputs": [
      "Hegni Ragnar",
      "Hegni",
      "Hogni",
      "Hogni Ragnar",
      "Dáinsleif",
      "black and white knights"
    ],
    "printed": [
      "Hegni",
      "Hegni Ragnar"
    ],
    "optional": [
      {
        "form": "Dáinsleif",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "black and white knights",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:heith-velvet",
    "name": "Heith Velvet",
    "category": "character",
    "inputs": [
      "Heith Velvet",
      "Heith",
      "Golden Witch",
      "Vana Mardel",
      "Vana Mardoll"
    ],
    "printed": [
      "Heith Velvet",
      "Heith",
      "Golden Witch",
      "Vana Mardel"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:helga",
    "name": "Helga",
    "category": "character",
    "inputs": [
      "Helga"
    ],
    "printed": [
      "Helga"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:hephaistos",
    "name": "Hephaistos",
    "category": "character",
    "inputs": [
      "Hephaistos",
      "HESPHAISTOS",
      "Hephaestus"
    ],
    "printed": [
      "Hephaistos",
      "HESPHAISTOS"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:hermes",
    "name": "Hermes",
    "category": "character",
    "inputs": [
      "Hermes"
    ],
    "printed": [
      "Hermes"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:hestia",
    "name": "Hestia",
    "category": "character",
    "inputs": [
      "Hestia",
      "Hesita",
      "Loli Big Boobs",
      "Loli Big Tits",
      "Loli Lady",
      "Itty-Bitty",
      "Vesta",
      "Shrimp"
    ],
    "printed": [
      "Hestia",
      "Hesita",
      "Loli Big Boobs",
      "Loli Big Tits",
      "Loli Lady",
      "Itty-Bitty"
    ],
    "optional": [
      {
        "form": "Vesta",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Shrimp",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:horn",
    "name": "Hörn",
    "category": "character",
    "inputs": [
      "Hörn",
      "Helen",
      "Horn",
      "Helun",
      "Herun",
      "Nameless",
      "Syr"
    ],
    "printed": [
      "Hörn",
      "Helen"
    ],
    "optional": [
      {
        "form": "Nameless",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Syr",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": "Some names or spellings can have other meanings. Check the surrounding context."
  },
  {
    "id": "character:hyacinthus",
    "name": "Hyacinthus",
    "category": "character",
    "inputs": [
      "Hyacinthus",
      "Phoebus Apollo",
      "Hyakinthos",
      "Hyakinthos Clio"
    ],
    "printed": [
      "Hyacinthus",
      "Phoebus Apollo"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:ibly-archer",
    "name": "Ibly Archer",
    "category": "character",
    "inputs": [
      "Ibly Archer",
      "Ibly",
      "Fire Inferno Flame",
      "Ibri",
      "Ibri Achaa"
    ],
    "printed": [
      "Ibly",
      "Ibly Archer",
      "Fire Inferno Flame"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:idun",
    "name": "Idun",
    "category": "character",
    "inputs": [
      "Idun"
    ],
    "printed": [
      "Idun"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:ikelos",
    "name": "Ikelos",
    "category": "character",
    "inputs": [
      "Ikelos"
    ],
    "printed": [
      "Ikelos"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:ishtar",
    "name": "Ishtar",
    "category": "character",
    "inputs": [
      "Ishtar",
      "goddess of beauty"
    ],
    "printed": [
      "Ishtar"
    ],
    "optional": [
      {
        "form": "goddess of beauty",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:iska",
    "name": "Iska",
    "category": "character",
    "inputs": [
      "Iska"
    ],
    "printed": [
      "Iska"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:jura-harma",
    "name": "Jura Harma",
    "category": "character",
    "inputs": [
      "Jura Harma",
      "Jura"
    ],
    "printed": [
      "Jura Harma",
      "Jura"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:kaguya-gojouno",
    "name": "Kaguya Gojouno",
    "category": "character",
    "inputs": [
      "Kaguya Gojouno",
      "Kaguya",
      "Gojouno Kaguya"
    ],
    "printed": [
      "Kaguya",
      "Kaguya Gojouno",
      "Gojouno Kaguya"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:kali",
    "name": "Kali",
    "category": "character",
    "inputs": [
      "Kali"
    ],
    "printed": [
      "Kali"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:kam",
    "name": "Kam",
    "category": "character",
    "inputs": [
      "Kam",
      "Caam"
    ],
    "printed": [
      "Kam"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:kanu",
    "name": "Kanu",
    "category": "character",
    "inputs": [
      "Kanu",
      "Canoe",
      "Canoe Belway"
    ],
    "printed": [
      "Kanu"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:laura",
    "name": "Laura",
    "category": "character",
    "inputs": [
      "Laura"
    ],
    "printed": [
      "Laura"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:laurier",
    "name": "Laurier",
    "category": "character",
    "inputs": [
      "Laurier"
    ],
    "printed": [
      "Laurier"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:leene-arshe",
    "name": "Leene Arshe",
    "category": "character",
    "inputs": [
      "Leene Arshe",
      "Leene",
      "Line",
      "Line Arshe"
    ],
    "printed": [
      "Leene",
      "Leene Arshe"
    ],
    "optional": [],
    "caution": "Some names or spellings can have other meanings. Check the surrounding context."
  },
  {
    "id": "character:lefiya-viridis",
    "name": "Lefiya Viridis",
    "category": "character",
    "inputs": [
      "Lefiya Viridis",
      "Lefiya",
      "Thousand Elf",
      "Thousand"
    ],
    "printed": [
      "Lefiya",
      "Lefiya Viridis"
    ],
    "optional": [
      {
        "form": "Thousand Elf",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Thousand",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:lena-tully",
    "name": "Lena Tully",
    "category": "character",
    "inputs": [
      "Lena Tully",
      "Lena",
      "Rena",
      "Lena Tally"
    ],
    "printed": [
      "Lena",
      "Lena Tully",
      "Rena"
    ],
    "optional": [],
    "caution": "Some names or spellings can have other meanings. Check the surrounding context."
  },
  {
    "id": "character:lenoa",
    "name": "Lenoa",
    "category": "character",
    "inputs": [
      "Lenoa"
    ],
    "printed": [
      "Lenoa"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:leon-verdenberg",
    "name": "Leon Verdenberg",
    "category": "character",
    "inputs": [
      "Leon Verdenberg",
      "Knight of Knights",
      "Ultra Page",
      "Leon Vardenburg",
      "Leon"
    ],
    "printed": [
      "Leon Verdenberg",
      "Knight of Knights",
      "Ultra Page"
    ],
    "optional": [
      {
        "form": "Leon",
        "caution": "Shared by Ryuu and Leon Verdenberg. Matches may refer to either character."
      }
    ],
    "caution": "Leon is shared by Ryuu and Leon Verdenberg. It is available separately below, not included with the name variants."
  },
  {
    "id": "character:levis",
    "name": "Levis",
    "category": "character",
    "inputs": [
      "Levis",
      "Revis"
    ],
    "printed": [
      "Levis"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:lidari",
    "name": "Lidari",
    "category": "character",
    "inputs": [
      "Lidari"
    ],
    "printed": [
      "Lidari"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:lido",
    "name": "Lido",
    "category": "character",
    "inputs": [
      "Lido",
      "Lyd"
    ],
    "printed": [
      "Lido"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:lilliluka-erde",
    "name": "Lilliluka Erde",
    "category": "character",
    "inputs": [
      "Lilliluka Erde",
      "Lilliluka",
      "Lilly",
      "Little Marshal",
      "Liliruca",
      "Liliruca Arde",
      "Little Marshall"
    ],
    "printed": [
      "Lilliluka",
      "Lilliluka Erde",
      "Lilly",
      "Little Marshal"
    ],
    "optional": [],
    "caution": "Some names or spellings can have other meanings. Check the surrounding context."
  },
  {
    "id": "character:lissos",
    "name": "Lissos",
    "category": "character",
    "inputs": [
      "Lissos"
    ],
    "printed": [
      "Lissos"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:loki",
    "name": "Loki",
    "category": "character",
    "inputs": [
      "Loki",
      "Trickster",
      "Loki No Bits"
    ],
    "printed": [
      "Loki",
      "Trickster",
      "Loki No Bits"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:luan-espel",
    "name": "Luan Espel",
    "category": "character",
    "inputs": [
      "Luan Espel",
      "Luan"
    ],
    "printed": [
      "Luan Espel",
      "Luan"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:luke-fowl",
    "name": "Luke Fowl",
    "category": "character",
    "inputs": [
      "Luke Fowl",
      "Luke",
      "Rook"
    ],
    "printed": [
      "Luke",
      "Luke Fowl",
      "Rook"
    ],
    "optional": [],
    "caution": "Some names or spellings can have other meanings. Check the surrounding context."
  },
  {
    "id": "character:lulune-louie",
    "name": "Lulune Louie",
    "category": "character",
    "inputs": [
      "Lulune Louie",
      "Lulune",
      "Mud Hound Madl",
      "Madl",
      "Muddle"
    ],
    "printed": [
      "Lulune Louie",
      "Lulune",
      "Mud Hound Madl",
      "Madl"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:luvis",
    "name": "Luvis",
    "category": "character",
    "inputs": [
      "Luvis",
      "Ruvis",
      "Luvis Lilix"
    ],
    "printed": [
      "Luvis",
      "Ruvis",
      "Luvis Lilix"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:lyana",
    "name": "Lyana",
    "category": "character",
    "inputs": [
      "Lyana"
    ],
    "printed": [
      "Lyana"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:lyra",
    "name": "Lyra",
    "category": "character",
    "inputs": [
      "Lyra",
      "Slyle",
      "Thrail"
    ],
    "printed": [
      "Lyra",
      "Slyle"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:mari",
    "name": "Mari",
    "category": "character",
    "inputs": [
      "Mari",
      "Marie"
    ],
    "printed": [
      "Mari"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:maria",
    "name": "Maria",
    "category": "character",
    "inputs": [
      "Maria"
    ],
    "printed": [
      "Maria"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:maris-hackard",
    "name": "Maris Hackard",
    "category": "character",
    "inputs": [
      "Maris Hackard",
      "Maris"
    ],
    "printed": [
      "Maris Hackard",
      "Maris"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:marius-victrix-rakia",
    "name": "Marius Victrix Rakia",
    "category": "character",
    "inputs": [
      "Marius Victrix Rakia",
      "Marius"
    ],
    "printed": [
      "Marius Victrix Rakia",
      "Marius"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:marta",
    "name": "Marta",
    "category": "character",
    "inputs": [
      "Marta"
    ],
    "printed": [
      "Marta"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:maryu",
    "name": "Maryu",
    "category": "character",
    "inputs": [
      "Maryu"
    ],
    "printed": [
      "Maryu"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:maxim",
    "name": "Maxim",
    "category": "character",
    "inputs": [
      "Maxim"
    ],
    "printed": [
      "Maxim"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:melissa",
    "name": "Melissa",
    "category": "character",
    "inputs": [
      "Melissa"
    ],
    "printed": [
      "Melissa"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:merrill",
    "name": "Merrill",
    "category": "character",
    "inputs": [
      "Merrill"
    ],
    "printed": [
      "Merrill"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:mia",
    "name": "Mia",
    "category": "character",
    "inputs": [
      "Mia",
      "Mia Grand",
      "Demi Ymir",
      "Mama Mia"
    ],
    "printed": [
      "Mia",
      "Mia Grand",
      "Demi Ymir",
      "Mama Mia"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:miach",
    "name": "Miach",
    "category": "character",
    "inputs": [
      "Miach"
    ],
    "printed": [
      "Miach"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:mikoto-yamato",
    "name": "Mikoto Yamato",
    "category": "character",
    "inputs": [
      "Mikoto Yamato",
      "Mikoto",
      "Yamato Mikoto",
      "Eternal † Shadow",
      "Eternal Shadow",
      "Absolute✝Shadow"
    ],
    "printed": [
      "Mikoto",
      "Mikoto Yamato",
      "Yamato Mikoto",
      "Eternal † Shadow",
      "Eternal Shadow"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:miliria",
    "name": "Miliria",
    "category": "character",
    "inputs": [
      "Miliria"
    ],
    "printed": [
      "Miliria"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:misha-frot",
    "name": "Misha Frot",
    "category": "character",
    "inputs": [
      "Misha Frot",
      "Misha",
      "Misha Flott"
    ],
    "printed": [
      "Misha",
      "Misha Frot"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:modaka",
    "name": "Modaka",
    "category": "character",
    "inputs": [
      "Modaka",
      "Modak"
    ],
    "printed": [
      "Modaka",
      "Modak"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:mord",
    "name": "Mord",
    "category": "character",
    "inputs": [
      "Mord",
      "Mord Latro"
    ],
    "printed": [
      "Mord",
      "Mord Latro"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:nahza-ersuis",
    "name": "Nahza Ersuis",
    "category": "character",
    "inputs": [
      "Nahza Ersuis",
      "Nahza",
      "Naaza",
      "Naaza Erisuis"
    ],
    "printed": [
      "Nahza"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:narfi",
    "name": "Narfi",
    "category": "character",
    "inputs": [
      "Narfi",
      "Narvi",
      "Narvi Roll"
    ],
    "printed": [
      "Narfi"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:naruru",
    "name": "Naruru",
    "category": "character",
    "inputs": [
      "Naruru"
    ],
    "printed": [
      "Naruru"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:nassen",
    "name": "Nassen",
    "category": "character",
    "inputs": [
      "Nassen"
    ],
    "printed": [
      "Nassen"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:natalinoe-cladfield",
    "name": "Natalinoe Cladfield",
    "category": "character",
    "inputs": [
      "Natalinoe Cladfield",
      "Natalinoe"
    ],
    "printed": [
      "Natalinoe Cladfield",
      "Natalinoe"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:nelly",
    "name": "Nelly",
    "category": "character",
    "inputs": [
      "Nelly"
    ],
    "printed": [
      "Nelly"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:nernati",
    "name": "Nernati",
    "category": "character",
    "inputs": [
      "Nernati",
      "Nerti",
      "Nernatti"
    ],
    "printed": [
      "Nernati",
      "Nerti"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:neze",
    "name": "Neze",
    "category": "character",
    "inputs": [
      "Neze"
    ],
    "printed": [
      "Neze"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:nina-tulle",
    "name": "Nina Tulle",
    "category": "character",
    "inputs": [
      "Nina Tulle",
      "Nina"
    ],
    "printed": [
      "Nina Tulle",
      "Nina"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:njordr",
    "name": "Njörðr",
    "category": "character",
    "inputs": [
      "Njörðr",
      "Njrðr",
      "Njǫrðr",
      "Njord"
    ],
    "printed": [
      "Njörðr",
      "Njrðr",
      "Njǫrðr"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:noin",
    "name": "Noin",
    "category": "character",
    "inputs": [
      "Noin"
    ],
    "printed": [
      "Noin"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:noruru",
    "name": "Noruru",
    "category": "character",
    "inputs": [
      "Noruru"
    ],
    "printed": [
      "Noruru"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:odin",
    "name": "Odin",
    "category": "character",
    "inputs": [
      "Odin"
    ],
    "printed": [
      "Odin"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:olba",
    "name": "Olba",
    "category": "character",
    "inputs": [
      "Olba"
    ],
    "printed": [
      "Olba"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:olivas-act",
    "name": "Olivas Act",
    "category": "character",
    "inputs": [
      "Olivas Act",
      "Olivas",
      "Vendetta",
      "White Devil"
    ],
    "printed": [
      "Olivas Act",
      "Olivas",
      "Vendetta",
      "White Devil"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:ossian",
    "name": "Ossian",
    "category": "character",
    "inputs": [
      "Ossian"
    ],
    "printed": [
      "Ossian"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:ottar",
    "name": "Ottar",
    "category": "character",
    "inputs": [
      "Ottar",
      "Warlord"
    ],
    "printed": [
      "Ottar",
      "Warlord"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:ouka-kashima",
    "name": "Ouka Kashima",
    "category": "character",
    "inputs": [
      "Ouka Kashima",
      "Ouka",
      "Masuratakeo",
      "Kashima Ouka"
    ],
    "printed": [
      "Ouka",
      "Ouka Kashima",
      "Masuratakeo"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:ouranos",
    "name": "Ouranos",
    "category": "character",
    "inputs": [
      "Ouranos",
      "Uranus",
      "Father of Orario"
    ],
    "printed": [
      "Ouranos",
      "Uranus",
      "Father of Orario"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:penia",
    "name": "Penia",
    "category": "character",
    "inputs": [
      "Penia"
    ],
    "printed": [
      "Penia"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:phobos",
    "name": "Phobos",
    "category": "character",
    "inputs": [
      "Phobos"
    ],
    "printed": [
      "Phobos"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:phryne-jamil",
    "name": "Phryne Jamil",
    "category": "character",
    "inputs": [
      "Phryne Jamil",
      "Phryne",
      "Androctonus",
      "Man Slayer"
    ],
    "printed": [
      "Phryne Jamil",
      "Phryne",
      "Androctonus"
    ],
    "optional": [
      {
        "form": "Man Slayer",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:plutus",
    "name": "Plutus",
    "category": "character",
    "inputs": [
      "Plutus"
    ],
    "printed": [
      "Plutus"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:rafale-ljos-alf",
    "name": "Rafale Ljos Alf",
    "category": "character",
    "inputs": [
      "Rafale Ljos Alf",
      "Rafale",
      "Larfal",
      "Larfal Ljos Alf"
    ],
    "printed": [
      "Rafale",
      "Rafale Ljos Alf"
    ],
    "optional": [],
    "caution": "Some names or spellings can have other meanings. Check the surrounding context."
  },
  {
    "id": "character:rakuta",
    "name": "Rakuta",
    "category": "character",
    "inputs": [
      "Rakuta",
      "Rakta",
      "Rakta Haze"
    ],
    "printed": [
      "Rakuta"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:raul-nord",
    "name": "Raul Nord",
    "category": "character",
    "inputs": [
      "Raul Nord",
      "Raul",
      "High Novice"
    ],
    "printed": [
      "Raul Nord",
      "Raul",
      "High Novice"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:rehmer",
    "name": "Rehmer",
    "category": "character",
    "inputs": [
      "Rehmer"
    ],
    "printed": [
      "Rehmer"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:rei",
    "name": "Rei",
    "category": "character",
    "inputs": [
      "Rei",
      "Ray"
    ],
    "printed": [
      "Rei"
    ],
    "optional": [],
    "caution": "Some names or spellings can have other meanings. Check the surrounding context."
  },
  {
    "id": "character:resheph",
    "name": "Resheph",
    "category": "character",
    "inputs": [
      "Resheph"
    ],
    "printed": [
      "Resheph"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:rethusa",
    "name": "Rethusa",
    "category": "character",
    "inputs": [
      "Rethusa"
    ],
    "printed": [
      "Rethusa"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:rina",
    "name": "Rina",
    "category": "character",
    "inputs": [
      "Rina"
    ],
    "printed": [
      "Rina"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:riveria-ljos-alf",
    "name": "Riveria Ljos Alf",
    "category": "character",
    "inputs": [
      "Riveria Ljos Alf",
      "Riveria",
      "Reveria",
      "Riviera",
      "Nine Hell",
      "Reveria Riyos Ahrve",
      "Riyos Ahrve"
    ],
    "printed": [
      "Riveria",
      "Riveria Ljos Alf",
      "Reveria",
      "Riviera",
      "Nine Hell"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:rose",
    "name": "Rose",
    "category": "character",
    "inputs": [
      "Rose",
      "Rose Fannett"
    ],
    "printed": [
      "Rose"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:royman-mardeel",
    "name": "Royman Mardeel",
    "category": "character",
    "inputs": [
      "Royman Mardeel",
      "Royman",
      "Guild’s Pig"
    ],
    "printed": [
      "Royman Mardeel",
      "Royman",
      "Guild’s Pig"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:rubart-ryan",
    "name": "Rubart Ryan",
    "category": "character",
    "inputs": [
      "Rubart Ryan",
      "Rubart"
    ],
    "printed": [
      "Rubart Ryan",
      "Rubart"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:runoa-faust",
    "name": "Runoa Faust",
    "category": "character",
    "inputs": [
      "Runoa Faust",
      "Runoa",
      "Ruona",
      "Lunoire",
      "Lunoire Faust",
      "Faust",
      "Black Fist"
    ],
    "printed": [
      "Runoa",
      "Runoa Faust",
      "Ruona"
    ],
    "optional": [
      {
        "form": "Faust",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Black Fist",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:ryuu-lion",
    "name": "Ryuu Lion",
    "category": "character",
    "inputs": [
      "Ryuu Lion",
      "Lyu",
      "Lyu Lyon",
      "Lyu Leon",
      "Ryu",
      "Gale Wind",
      "Lyu Astrea",
      "Ryuu",
      "Ryu Lion",
      "Leon",
      "Gale"
    ],
    "printed": [
      "Lyu",
      "Lyu Lyon",
      "Lyu Leon",
      "Ryu",
      "Gale Wind",
      "Lyu Astrea"
    ],
    "optional": [
      {
        "form": "Leon",
        "caution": "Shared by Ryuu and Leon Verdenberg. Matches may refer to either character."
      },
      {
        "form": "Gale",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": "Leon is shared by Ryuu and Leon Verdenberg. It is available separately below, not included with the name variants."
  },
  {
    "id": "character:samira",
    "name": "Samira",
    "category": "character",
    "inputs": [
      "Samira"
    ],
    "printed": [
      "Samira"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:scott",
    "name": "Scott",
    "category": "character",
    "inputs": [
      "Scott",
      "Scoot"
    ],
    "printed": [
      "Scott",
      "Scoot"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:seldia",
    "name": "Seldia",
    "category": "character",
    "inputs": [
      "Seldia",
      "Celdia"
    ],
    "printed": [
      "Seldia",
      "Celdia"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:shakti-varma",
    "name": "Shakti Varma",
    "category": "character",
    "inputs": [
      "Shakti Varma",
      "Shakti",
      "Ankusha"
    ],
    "printed": [
      "Shakti Varma",
      "Shakti",
      "Ankusha"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:sharon",
    "name": "Sharon",
    "category": "character",
    "inputs": [
      "Sharon"
    ],
    "printed": [
      "Sharon"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:soma",
    "name": "Soma",
    "category": "character",
    "inputs": [
      "Soma"
    ],
    "printed": [
      "Soma"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:sophie",
    "name": "Sophie",
    "category": "character",
    "inputs": [
      "Sophie"
    ],
    "printed": [
      "Sophie"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:syr-flover",
    "name": "Syr Flover",
    "category": "character",
    "inputs": [
      "Syr Flover",
      "Syr",
      "Syr Flova"
    ],
    "printed": [
      "Syr",
      "Syr Flover"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:takemikazuchi",
    "name": "Takemikazuchi",
    "category": "character",
    "inputs": [
      "Takemikazuchi"
    ],
    "printed": [
      "Takemikazuchi"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:talvi",
    "name": "Talvi",
    "category": "character",
    "inputs": [
      "Talvi"
    ],
    "printed": [
      "Talvi"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:tammuz-berrilli",
    "name": "Tammuz Berrilli",
    "category": "character",
    "inputs": [
      "Tammuz Berrilli",
      "Tammuz",
      "Tammuz Belili"
    ],
    "printed": [
      "Tammuz",
      "Tammuz Berrilli"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:ted",
    "name": "Ted",
    "category": "character",
    "inputs": [
      "Ted",
      "Terry",
      "Terry Cervantes"
    ],
    "printed": [
      "Ted"
    ],
    "optional": [
      {
        "form": "Terry",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      },
      {
        "form": "Terry Cervantes",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:terry-cervantes",
    "name": "Terry Cervantes",
    "category": "character",
    "inputs": [
      "Terry Cervantes",
      "Terry"
    ],
    "printed": [
      "Terry Cervantes",
      "Terry"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:thanatos",
    "name": "Thanatos",
    "category": "character",
    "inputs": [
      "Thanatos"
    ],
    "printed": [
      "Thanatos"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:tiona-hyrute",
    "name": "Tiona Hyrute",
    "category": "character",
    "inputs": [
      "Tiona Hyrute",
      "Tiona",
      "Amazon the Slasher",
      "Tiona Hiryute",
      "Amazon"
    ],
    "printed": [
      "Tiona",
      "Tiona Hyrute",
      "Amazon the Slasher"
    ],
    "optional": [
      {
        "form": "Amazon",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:tione-hyrute",
    "name": "Tione Hyrute",
    "category": "character",
    "inputs": [
      "Tione Hyrute",
      "Tione",
      "Jormungand",
      "Tione Hiryute"
    ],
    "printed": [
      "Tione",
      "Tione Hyrute",
      "Jormungand"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:tsubaki-collbrande",
    "name": "Tsubaki Collbrande",
    "category": "character",
    "inputs": [
      "Tsubaki Collbrande",
      "Tsubaki",
      "Cyclops"
    ],
    "printed": [
      "Tsubaki",
      "Tsubaki Collbrande"
    ],
    "optional": [
      {
        "form": "Cyclops",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:turk-sledd",
    "name": "Turk Sledd",
    "category": "character",
    "inputs": [
      "Turk Sledd",
      "Turk"
    ],
    "printed": [
      "Turk Sledd",
      "Turk"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:valletta-grede",
    "name": "Valletta Grede",
    "category": "character",
    "inputs": [
      "Valletta Grede",
      "Valletta",
      "Arachnia"
    ],
    "printed": [
      "Valletta Grede",
      "Valletta",
      "Arachnia"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:van",
    "name": "Van",
    "category": "character",
    "inputs": [
      "Van"
    ],
    "printed": [
      "Van"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:vidarr",
    "name": "Víðarr",
    "category": "character",
    "inputs": [
      "Víðarr",
      "Vidar"
    ],
    "printed": [
      "Víðarr",
      "Vidar"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:vito",
    "name": "Vito",
    "category": "character",
    "inputs": [
      "Vito",
      "Faceless"
    ],
    "printed": [
      "Vito",
      "Faceless"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:welf-crozzo",
    "name": "Welf Crozzo",
    "category": "character",
    "inputs": [
      "Welf Crozzo",
      "Welf",
      "Welf Krozzo",
      "Ignis"
    ],
    "printed": [
      "Welf",
      "Welf Crozzo",
      "Welf Krozzo"
    ],
    "optional": [
      {
        "form": "Ignis",
        "caution": "May refer to another character, a spell, or an ordinary word. Check the surrounding context."
      }
    ],
    "caution": ""
  },
  {
    "id": "character:wiene",
    "name": "Wiene",
    "category": "character",
    "inputs": [
      "Wiene",
      "Winne",
      "Weine"
    ],
    "printed": [
      "Wiene",
      "Winne",
      "Weine"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:wil-crozzo",
    "name": "Wil Crozzo",
    "category": "character",
    "inputs": [
      "Wil Crozzo",
      "Wil",
      "Vil Crozzo",
      "Vil"
    ],
    "printed": [
      "Wil Crozzo",
      "Wil",
      "Vil Crozzo",
      "Vil"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:yorger",
    "name": "Yorger",
    "category": "character",
    "inputs": [
      "Yorger"
    ],
    "printed": [
      "Yorger"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:yufie",
    "name": "Yufie",
    "category": "character",
    "inputs": [
      "Yufie",
      "Yuffie"
    ],
    "printed": [
      "Yufie"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:zald",
    "name": "Zald",
    "category": "character",
    "inputs": [
      "Zald",
      "Glutton",
      "Zard",
      "Gluttony"
    ],
    "printed": [
      "Zald",
      "Glutton"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:zanis-lustra",
    "name": "Zanis Lustra",
    "category": "character",
    "inputs": [
      "Zanis Lustra",
      "Zanis",
      "Gandharva",
      "Wine-Guardian"
    ],
    "printed": [
      "Zanis Lustra",
      "Zanis",
      "Gandharva",
      "Wine-Guardian"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "character:zeus",
    "name": "Zeus",
    "category": "character",
    "inputs": [
      "Zeus"
    ],
    "printed": [
      "Zeus"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "magic:magic-rea-laevateinn",
    "name": "Rea Laevateinn",
    "category": "magic",
    "inputs": [
      "Rea Laevateinn",
      "Rae Laevateinn"
    ],
    "printed": [
      "Rea Laevateinn",
      "Rae Laevateinn"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "magic:magic-noa-heal",
    "name": "Noa Heal",
    "category": "magic",
    "inputs": [
      "Noa Heal",
      "Noah Heal"
    ],
    "printed": [
      "Noa Heal",
      "Noah Heal"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "magic:magic-magia-kris",
    "name": "Magia Kris",
    "category": "magic",
    "inputs": [
      "Magia Kris",
      "Magia Kreis"
    ],
    "printed": [
      "Magia Kris",
      "Magia Kreis"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "magic:magic-airiel",
    "name": "Airiel",
    "category": "magic",
    "inputs": [
      "Airiel",
      "Ariel"
    ],
    "printed": [
      "Airiel"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "magic:magic-futsu-no-mitama",
    "name": "Futsu no Mitama",
    "category": "magic",
    "inputs": [
      "Futsu no Mitama",
      "Futsu no Tama",
      "Futsunomitama"
    ],
    "printed": [
      "Futsu no Mitama",
      "Futsu no Tama"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "magic:magic-will-o-the-wisp",
    "name": "Will-o'-the-Wisp",
    "category": "magic",
    "inputs": [
      "Will-o'-the-Wisp",
      "Will-o’-the-Wisp",
      "Will-o-Wisp",
      "Will-o’-Wisp",
      "Will-o'-Wisp"
    ],
    "printed": [
      "Will-o’-the-Wisp",
      "Will-o-Wisp"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "magic:magic-dia-frater",
    "name": "Dia Frater",
    "category": "magic",
    "inputs": [
      "Dia Frater",
      "Dia Fratel"
    ],
    "printed": [
      "Dia Frater"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "magic:magic-dia-panacea",
    "name": "Dia Panacea",
    "category": "magic",
    "inputs": [
      "Dia Panacea",
      "Dia Panakeia"
    ],
    "printed": [
      "Dia Panacea"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "magic:magic-restrict-iorum",
    "name": "Restrict Iorum",
    "category": "magic",
    "inputs": [
      "Restrict Iorum",
      "List Iorum"
    ],
    "printed": [
      "Restrict Iorum"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "magic:magic-velgas",
    "name": "Velgas",
    "category": "magic",
    "inputs": [
      "Velgas",
      "Velgus"
    ],
    "printed": [
      "Velgas"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "magic:magic-soul-light",
    "name": "Soul Light",
    "category": "magic",
    "inputs": [
      "Soul Light",
      "Soullight"
    ],
    "printed": [
      "Soul Light"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "magic:magic-fire-storm",
    "name": "Fire Storm",
    "category": "magic",
    "inputs": [
      "Fire Storm",
      "Firestorm"
    ],
    "printed": [
      "Fire Storm"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "magic:magic-astrea-record",
    "name": "Astrea Record",
    "category": "magic",
    "inputs": [
      "Astrea Record",
      "Astraea Record"
    ],
    "printed": [
      "Astrea Record"
    ],
    "optional": [],
    "caution": "These words also have other meanings. Results are literal matches; check the surrounding context."
  },
  {
    "id": "magic:magic-remisto-felis",
    "name": "Remisto Felis",
    "category": "magic",
    "inputs": [
      "Remisto Felis",
      "Remiste Felis"
    ],
    "printed": [
      "Remisto Felis"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "magic:magic-vana-seidr",
    "name": "Vana Seiðr",
    "category": "magic",
    "inputs": [
      "Vana Seiðr",
      "Vana Seidr"
    ],
    "printed": [
      "Vana Seiðr"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "magic:magic-dainsleif",
    "name": "Dáinsleif",
    "category": "magic",
    "inputs": [
      "Dáinsleif",
      "Dainsleif"
    ],
    "printed": [
      "Dáinsleif"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "skill:skill-liaris-freese",
    "name": "Liaris Freese",
    "category": "skill",
    "inputs": [
      "Liaris Freese",
      "Realis Phrase"
    ],
    "printed": [
      "Liaris Freese",
      "Realis Phrase"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "skill:skill-double-cannon",
    "name": "Double Cannon",
    "category": "skill",
    "inputs": [
      "Double Cannon",
      "Double Canon"
    ],
    "printed": [
      "Double Cannon",
      "Double Canon"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "skill:skill-laurel-wreath",
    "name": "Laurel Wreath",
    "category": "skill",
    "inputs": [
      "Laurel Wreath",
      "Laurus Wreath"
    ],
    "printed": [
      "Laurel Wreath"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "skill:skill-mikuzume-no-hou",
    "name": "Mikuzume no Hou",
    "category": "skill",
    "inputs": [
      "Mikuzume no Hou",
      "Mikuzumenohou"
    ],
    "printed": [
      "Mikuzume no Hou"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "skill:skill-yatano-black-crow",
    "name": "Yatano Black Crow",
    "category": "skill",
    "inputs": [
      "Yatano Black Crow",
      "Yatanokurogarasu"
    ],
    "printed": [
      "Yatano Black Crow"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "skill:skill-yatano-white-crow",
    "name": "Yatano White Crow",
    "category": "skill",
    "inputs": [
      "Yatano White Crow",
      "Yatanoshirogarasu"
    ],
    "printed": [
      "Yatano White Crow"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "divine_attribute:divine_attribute-eyes-of-insight",
    "name": "Eyes of Insight",
    "category": "divine_attribute",
    "inputs": [
      "Eyes of Insight",
      "Acumen Eyes"
    ],
    "printed": [
      "Eyes of Insight",
      "Acumen Eyes"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "development_ability:development_ability-mage",
    "name": "Mage",
    "category": "development_ability",
    "inputs": [
      "Mage",
      "Conjure",
      "Magic Control"
    ],
    "printed": [
      "Mage",
      "Conjure",
      "Magic Control"
    ],
    "optional": [],
    "caution": "These words also have other meanings. Results are literal matches; check the surrounding context."
  },
  {
    "id": "development_ability:development_ability-mystery",
    "name": "Mystery",
    "category": "development_ability",
    "inputs": [
      "Mystery",
      "Enigma"
    ],
    "printed": [
      "Mystery",
      "Enigma"
    ],
    "optional": [],
    "caution": "These words also have other meanings. Results are literal matches; check the surrounding context."
  },
  {
    "id": "development_ability:development_ability-blacksmith",
    "name": "Blacksmith",
    "category": "development_ability",
    "inputs": [
      "Blacksmith",
      "Forge"
    ],
    "printed": [
      "Forge"
    ],
    "optional": [],
    "caution": "These words also have other meanings. Results are literal matches; check the surrounding context."
  },
  {
    "id": "development_ability:development_ability-mixing",
    "name": "Mixing",
    "category": "development_ability",
    "inputs": [
      "Mixing",
      "Synthesize",
      "Compounding"
    ],
    "printed": [
      "Synthesize",
      "Compounding"
    ],
    "optional": [],
    "caution": "These words also have other meanings. Results are literal matches; check the surrounding context."
  },
  {
    "id": "development_ability:development_ability-abnormal-resistance",
    "name": "Abnormal Resistance",
    "category": "development_ability",
    "inputs": [
      "Abnormal Resistance",
      "Immunity",
      "Resistance"
    ],
    "printed": [
      "Abnormal Resistance",
      "Immunity",
      "Resistance"
    ],
    "optional": [],
    "caution": "These words also have other meanings. Results are literal matches; check the surrounding context."
  },
  {
    "id": "development_ability:development_ability-magic-resistance",
    "name": "Magic Resistance",
    "category": "development_ability",
    "inputs": [
      "Magic Resistance",
      "Magic Defense"
    ],
    "printed": [
      "Magic Resistance",
      "Magic Defense"
    ],
    "optional": [],
    "caution": "These words also have other meanings. Results are literal matches; check the surrounding context."
  },
  {
    "id": "status_field:status_field-defense",
    "name": "Defense",
    "category": "status_field",
    "inputs": [
      "Defense",
      "Endurance"
    ],
    "printed": [
      "Defense",
      "Endurance"
    ],
    "optional": [],
    "caution": "These words also have other meanings. Results are literal matches; check the surrounding context."
  },
  {
    "id": "status_field:status_field-utility",
    "name": "Utility",
    "category": "status_field",
    "inputs": [
      "Utility",
      "Dexterity"
    ],
    "printed": [
      "Utility",
      "Dexterity"
    ],
    "optional": [],
    "caution": "These words also have other meanings. Results are literal matches; check the surrounding context."
  },
  {
    "id": "item:item-silence-lyra",
    "name": "Silence Lyra",
    "category": "item",
    "inputs": [
      "Silence Lyra",
      "Silence Lyre"
    ],
    "printed": [
      "Silence Lyra",
      "Silence Lyre"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-shikou-kazuki",
    "name": "Shikou Kazuki",
    "category": "item",
    "inputs": [
      "Shikou Kazuki",
      "Shikou-Kazuki"
    ],
    "printed": [
      "Shikou Kazuki",
      "Shikou-Kazuki"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-little-barista",
    "name": "Little Barista",
    "category": "item",
    "inputs": [
      "Little Barista",
      "LITTLE • BARISTA",
      "Little Ballista"
    ],
    "printed": [
      "LITTLE • BARISTA",
      "Little Ballista"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-frosvirt",
    "name": "Frosvirt",
    "category": "item",
    "inputs": [
      "Frosvirt",
      "Flosvirt"
    ],
    "printed": [
      "Frosvirt"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-alvs-lumina",
    "name": "Alvs Lumina",
    "category": "item",
    "inputs": [
      "Alvs Lumina",
      "Alf's Lumina",
      "Alf’s Lumina"
    ],
    "printed": [
      "Alvs Lumina"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-forest-s-teardrop",
    "name": "Forest's Teardrop",
    "category": "item",
    "inputs": [
      "Forest's Teardrop",
      "Forest’s Teardrop",
      "Forest Teardrop"
    ],
    "printed": [
      "Forest’s Teardrop",
      "Forest Teardrop"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-solar-flamberge",
    "name": "Solar Flamberge",
    "category": "item",
    "inputs": [
      "Solar Flamberge",
      "Sun's Flamberge",
      "Sun’s Flamberge"
    ],
    "printed": [
      "Solar Flamberge"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-sword-air",
    "name": "Sword Air",
    "category": "item",
    "inputs": [
      "Sword Air",
      "Sword Ale"
    ],
    "printed": [
      "Sword Air"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-kaminari-ikazuchi-maru",
    "name": "Kaminari-Ikazuchi-Maru",
    "category": "item",
    "inputs": [
      "Kaminari-Ikazuchi-Maru",
      "Kaminari Ikazuchimaru"
    ],
    "printed": [
      "Kaminari-Ikazuchi-Maru"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-ushiwakamaru-nishiki",
    "name": "Ushiwakamaru-Nishiki",
    "category": "item",
    "inputs": [
      "Ushiwakamaru-Nishiki",
      "Ushiwakamaru-Shiki",
      "Ushiwakamarunishiki"
    ],
    "printed": [
      "Ushiwakamaru-Nishiki",
      "Ushiwakamaru-Shiki"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-roland-blade",
    "name": "Roland Blade",
    "category": "item",
    "inputs": [
      "Roland Blade",
      "Blade Rolan"
    ],
    "printed": [
      "Roland Blade"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-dual-roland",
    "name": "Dual Roland",
    "category": "item",
    "inputs": [
      "Dual Roland",
      "Dual Rolan"
    ],
    "printed": [
      "Dual Roland"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-roland-ax",
    "name": "Roland Ax",
    "category": "item",
    "inputs": [
      "Roland Ax",
      "Axe Rolan"
    ],
    "printed": [
      "Roland Ax"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-roland-spear",
    "name": "Roland Spear",
    "category": "item",
    "inputs": [
      "Roland Spear",
      "Spear Rolan"
    ],
    "printed": [
      "Roland Spear"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-roland-halberd",
    "name": "Roland Halberd",
    "category": "item",
    "inputs": [
      "Roland Halberd",
      "Halberd Rolan"
    ],
    "printed": [
      "Roland Halberd"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-protector-s-white-torch",
    "name": "Protector's White Torch",
    "category": "item",
    "inputs": [
      "Protector's White Torch",
      "Protector’s White Torch",
      "Guardian's White Torch",
      "Guardian’s White Torch"
    ],
    "printed": [
      "Protector’s White Torch"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-airgetlam",
    "name": "Airgetlám",
    "category": "item",
    "inputs": [
      "Airgetlám",
      "Airgetlam"
    ],
    "printed": [
      "Airgetlám"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-daedalus-orb",
    "name": "Daedalus Orb",
    "category": "item",
    "inputs": [
      "Daedalus Orb",
      "Daedalus’s Orb",
      "Daedalus's Orb"
    ],
    "printed": [
      "Daedalus Orb",
      "Daedalus’s Orb"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-legacy-of-daedalus",
    "name": "Legacy of Daedalus",
    "category": "item",
    "inputs": [
      "Legacy of Daedalus",
      "Daedalus Legacy"
    ],
    "printed": [
      "Legacy of Daedalus"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-killing-stone",
    "name": "Killing Stone",
    "category": "item",
    "inputs": [
      "Killing Stone",
      "Sesshouseki"
    ],
    "printed": [
      "Killing Stone",
      "Sesshouseki"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-oculus",
    "name": "Oculus",
    "category": "item",
    "inputs": [
      "Oculus",
      "oculus",
      "oculi",
      "Oculi"
    ],
    "printed": [
      "oculus",
      "oculi"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "item:item-corbel-edge",
    "name": "Corbel Edge",
    "category": "item",
    "inputs": [
      "Corbel Edge",
      "Corbel Edges"
    ],
    "printed": [
      "Corbel Edge",
      "Corbel Edges"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "material:material-mithril",
    "name": "Mithril",
    "category": "material",
    "inputs": [
      "Mithril",
      "mithril",
      "mythril",
      "Mythril"
    ],
    "printed": [
      "mithril",
      "mythril",
      "Mithril",
      "Mythril"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "material:material-damascus-steel",
    "name": "Damascus steel",
    "category": "material",
    "inputs": [
      "Damascus steel",
      "Damascus"
    ],
    "printed": [
      "Damascus steel",
      "Damascus"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "material:material-inferno-stone",
    "name": "Inferno Stone",
    "category": "material",
    "inputs": [
      "Inferno Stone",
      "Inferno Stones"
    ],
    "printed": [
      "Inferno Stone",
      "Inferno Stones"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "material:material-dir-adamantite",
    "name": "Dir Adamantite",
    "category": "material",
    "inputs": [
      "Dir Adamantite",
      "dir adamantite",
      "Dea Adamantite",
      "dea adamantite"
    ],
    "printed": [
      "dir adamantite"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "material:material-alb-s-pure-water",
    "name": "Alb's Pure Water",
    "category": "material",
    "inputs": [
      "Alb's Pure Water",
      "Alb’s Pure Water",
      "Alv Pure Water"
    ],
    "printed": [
      "Alb’s Pure Water"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-meren",
    "name": "Meren",
    "category": "location",
    "inputs": [
      "Meren",
      "Melen"
    ],
    "printed": [
      "Meren",
      "Melen"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-daedalus-street",
    "name": "Daedalus Street",
    "category": "location",
    "inputs": [
      "Daedalus Street",
      "Daidaros Street"
    ],
    "printed": [
      "Daedalus Street",
      "Daidaros Street"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-cafe-wish",
    "name": "Café Wish",
    "category": "location",
    "inputs": [
      "Café Wish",
      "Wish Café",
      "Cafe Wish",
      "Wish Cafe"
    ],
    "printed": [
      "Wish Café"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-deep-forest-seoro",
    "name": "Deep Forest Seoro",
    "category": "location",
    "inputs": [
      "Deep Forest Seoro",
      "Seolo Forest"
    ],
    "printed": [
      "Deep Forest Seoro"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-beor-mountains",
    "name": "Beor Mountains",
    "category": "location",
    "inputs": [
      "Beor Mountains",
      "Beor Mountain Range",
      "Beol Mountains"
    ],
    "printed": [
      "Beor Mountains",
      "Beor Mountain Range"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-zolingam",
    "name": "Zolingam",
    "category": "location",
    "inputs": [
      "Zolingam",
      "Solingen"
    ],
    "printed": [
      "Zolingam"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-lumirua-forest",
    "name": "Lumirua Forest",
    "category": "location",
    "inputs": [
      "Lumirua Forest",
      "Ryumilua Forest"
    ],
    "printed": [
      "Lumirua Forest"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-alf-royal-woods",
    "name": "Alf Royal Woods",
    "category": "location",
    "inputs": [
      "Alf Royal Woods",
      "Alf's Royal Forest",
      "Alf’s Royal Forest"
    ],
    "printed": [
      "Alf Royal Woods"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-karna",
    "name": "Karna",
    "category": "location",
    "inputs": [
      "Karna",
      "Karuna"
    ],
    "printed": [
      "Karna"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-lonza",
    "name": "Lonza",
    "category": "location",
    "inputs": [
      "Lonza",
      "Rhondda"
    ],
    "printed": [
      "Lonza"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-shalzad",
    "name": "Shalzad",
    "category": "location",
    "inputs": [
      "Shalzad",
      "Shalzard"
    ],
    "printed": [
      "Shalzad"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-warsa",
    "name": "Warsa",
    "category": "location",
    "inputs": [
      "Warsa",
      "Warusa"
    ],
    "printed": [
      "Warsa"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-leodo",
    "name": "Leodo",
    "category": "location",
    "inputs": [
      "Leodo",
      "Lioad Town"
    ],
    "printed": [
      "Leodo"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-dedyne",
    "name": "Dedyne",
    "category": "location",
    "inputs": [
      "Dedyne",
      "Dedine"
    ],
    "printed": [
      "Dedyne"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-noatun",
    "name": "Nóatún",
    "category": "location",
    "inputs": [
      "Nóatún",
      "Noatun"
    ],
    "printed": [
      "Nóatún"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-sessrumnir",
    "name": "Sessrúmnir",
    "category": "location",
    "inputs": [
      "Sessrúmnir",
      "Sessrumnir"
    ],
    "printed": [
      "Sessrúmnir"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-folkvangr",
    "name": "Folkvangr",
    "category": "location",
    "inputs": [
      "Folkvangr",
      "Fólkvangr"
    ],
    "printed": [
      "Folkvangr"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-benevolent-mistress",
    "name": "Benevolent Mistress",
    "category": "location",
    "inputs": [
      "Benevolent Mistress",
      "Hostess of Fertility"
    ],
    "printed": [
      "Benevolent Mistress"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-flaming-wasp",
    "name": "Flaming Wasp",
    "category": "location",
    "inputs": [
      "Flaming Wasp",
      "Hibachitei"
    ],
    "printed": [
      "Flaming Wasp",
      "Hibachitei"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-adventurers-graveyard",
    "name": "Adventurers Graveyard",
    "category": "location",
    "inputs": [
      "Adventurers Graveyard",
      "First Graveyard",
      "First Cemetery",
      "Adventurers' Graveyard",
      "Adventurers’ Graveyard"
    ],
    "printed": [
      "Adventurers Graveyard",
      "First Graveyard",
      "First Cemetery"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-pantheon",
    "name": "Pantheon",
    "category": "location",
    "inputs": [
      "Pantheon",
      "Guild Headquarters"
    ],
    "printed": [
      "Pantheon",
      "Guild Headquarters"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-pleasure-quarter",
    "name": "Pleasure Quarter",
    "category": "location",
    "inputs": [
      "Pleasure Quarter",
      "Pleasure District",
      "Night District"
    ],
    "printed": [
      "Pleasure Quarter",
      "Pleasure District",
      "Night District"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "organization:organization-astrea-familia",
    "name": "Astrea Familia",
    "category": "organization",
    "inputs": [
      "Astrea Familia",
      "Astraea Familia"
    ],
    "printed": [
      "Astrea Familia"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "organization:organization-hephaistos-familia",
    "name": "Hephaistos Familia",
    "category": "organization",
    "inputs": [
      "Hephaistos Familia",
      "Hephaestus Familia"
    ],
    "printed": [
      "Hephaistos Familia"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "organization:organization-vidar-familia",
    "name": "Vidar Familia",
    "category": "organization",
    "inputs": [
      "Vidar Familia",
      "Víðarr Familia",
      "Vidarr Familia"
    ],
    "printed": [
      "Vidar Familia",
      "Víðarr Familia"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "organization:organization-njord-familia",
    "name": "Njord Familia",
    "category": "organization",
    "inputs": [
      "Njord Familia",
      "Njörðr Familia",
      "Njǫrðr Familia"
    ],
    "printed": [
      "Njörðr Familia"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "organization:organization-evils",
    "name": "Evils",
    "category": "organization",
    "inputs": [
      "Evils",
      "Evilus"
    ],
    "printed": [
      "Evils"
    ],
    "optional": [],
    "caution": "These words also have other meanings. Results are literal matches; check the surrounding context."
  },
  {
    "id": "concept:concept-development-abilities",
    "name": "Development Abilities",
    "category": "concept",
    "inputs": [
      "Development Abilities",
      "Advanced Ability",
      "Advanced Abilities",
      "development ability",
      "development abilities",
      "Development Ability"
    ],
    "printed": [
      "Advanced Ability",
      "Advanced Abilities",
      "development ability",
      "development abilities"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "concept:concept-concurrent-casting",
    "name": "Concurrent Casting",
    "category": "concept",
    "inputs": [
      "Concurrent Casting",
      "concurrent casting",
      "concurrent chanting",
      "Concurrent Chanting"
    ],
    "printed": [
      "Concurrent Casting",
      "concurrent casting",
      "concurrent chanting"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "concept:concept-prum",
    "name": "Prum",
    "category": "concept",
    "inputs": [
      "Prum",
      "prum",
      "prums",
      "Prums",
      "pallum",
      "pallums",
      "Pallum",
      "Pallums"
    ],
    "printed": [
      "prum",
      "prums",
      "Prum",
      "Prums"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "concept:concept-demi-human",
    "name": "Demi-human",
    "category": "concept",
    "inputs": [
      "Demi-human",
      "demi-human",
      "demi-humans"
    ],
    "printed": [
      "demi-human",
      "demi-humans"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "concept:concept-valis",
    "name": "Valis",
    "category": "concept",
    "inputs": [
      "Valis",
      "valis",
      "vals",
      "VALS",
      "Vals",
      "vallis",
      "Vallis"
    ],
    "printed": [
      "valis",
      "Valis",
      "vals",
      "VALS"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "monster_type:monster_type-swordstag",
    "name": "Swordstag",
    "category": "monster_type",
    "inputs": [
      "Swordstag",
      "swordstag",
      "sword stag"
    ],
    "printed": [
      "swordstag",
      "sword stag"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "monster_type:monster_type-vouivre",
    "name": "Vouivre",
    "category": "monster_type",
    "inputs": [
      "Vouivre",
      "vouivre",
      "vouivres",
      "Vouivres",
      "vivre",
      "Vivre"
    ],
    "printed": [
      "vouivre",
      "Vouivre",
      "vouivres",
      "Vouivres"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "monster_type:monster_type-iguacu",
    "name": "Iguaçu",
    "category": "monster_type",
    "inputs": [
      "Iguaçu",
      "iguaçu",
      "iguacu",
      "Iguacu"
    ],
    "printed": [
      "iguaçu"
    ],
    "optional": [],
    "caution": ""
  },
  {
    "id": "location:location-alv-mountains",
    "name": "Alv Mountains",
    "category": "location",
    "inputs": [
      "Alv Mountains",
      "Alf Mountains"
    ],
    "printed": [
      "Alv Mountains"
    ],
    "optional": [],
    "caution": ""
  }
];
