import { readFile, writeFile } from 'node:fs/promises';

// Import only lookup metadata, never novel passages or local source paths.
const [charactersPath, otherPath] = process.argv.slice(2);
const characters = JSON.parse(await readFile(charactersPath, 'utf8'));
const other = JSON.parse(await readFile(otherPath, 'utf8'));
const entries = [];
for (const entity of [...characters.entities, ...other.entities]) {
  const category = entity.category || 'character';
  const allForms = entity.observedForms.map(item => item.form);
  // Search is case-insensitive: an ambiguous form cannot also be included
  // with ordinary variants just because its capitalization differs.
  const contextualForms = [...(entity.contextualAliases || []),
    ...entity.observedForms.filter(item => category === 'character' && item.matchPolicy === 'context_required')];
  const contextualKeys = new Set(contextualForms.map(item => item.form.trim().toLowerCase()));
  // Known attribution problems in the supplied inventory: keep query lookup,
  // but never suggest these strings as character evidence.
  const excluded = category === 'character'
    ? new Set(['Line', 'Horn', 'Ray', 'Astrea Record', ...(entity.id === 'leon-verdenberg' ? ['Leon'] : [])])
    : new Set();
  const printed = [...new Set(allForms.filter(form => !excluded.has(form) && !contextualKeys.has(form.trim().toLowerCase())))];
  if (!printed.length) throw new Error(`No safe printed forms for ${entity.id}`);
  const optional = [...new Map(contextualForms.map(item => [item.form.trim().toLowerCase(), item])).values()].map(item => ({
    form: item.form,
    caution: item.form === 'Leon'
      ? 'Shared by Ryuu and Leon Verdenberg. Matches may refer to either character.'
      : 'May refer to another character, a spell, or an ordinary word. Check the surrounding context.',
  }));
  entries.push({
    id: `${category}:${entity.id}`, name: entity.displayName, category,
    inputs: [...new Set([entity.displayName, ...allForms.filter(form => form !== 'Astrea Record' || category !== 'character'), ...entity.queryAliases.map(item => item.form), ...optional.map(item => item.form)])],
    printed, optional,
    caution: entity.matchPolicy === 'context_required'
      ? 'These words also have other meanings. Results are literal matches; check the surrounding context.'
      : ['leon-verdenberg', 'ryuu-lion'].includes(entity.id)
        ? 'Leon is shared by Ryuu and Leon Verdenberg. It is available separately below, not included with the name variants.'
        : entity.id === 'anya-fromel' ? ''
        : entity.warning ? 'Some names or spellings can have other meanings. Check the surrounding context.' : '',
  });
}
if (entries.length !== characters.entities.length + other.entities.length) throw new Error('Missing alias groups');
await writeFile('lib/alias-data.ts', `// Generated by scripts/build-aliases.mjs from the supplied alias inventories.\nexport const aliasData = ${JSON.stringify(entries, null, 2)};\n`);
console.log(`Imported ${characters.entities.length} character groups and ${other.entities.length} non-character groups.`);
